name: remote_control_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_gauges: ^23.1.40
  provider: 6.0.5
  flutter_blue_plus: ^1.20.4
  permission_handler: ^11.0.1
  kumi_popup_window: ^2.0.1
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: YoungSerif
      fonts:
        - asset: lib\fonts\YoungSerif-Regular.ttf
    - family: TiltNeon
      fonts:
        - asset: lib\fonts\TiltNeon-Regular.ttf

  assets:
    - assets\icons\Arfanify.png
    - assets\icons\Arfanify.svg
    - assets\json\map_style.json
