name: remote_control_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_gauges: ^24.2.6
  provider: ^6.1.1
  flutter_blue_plus: ^1.20.4
  permission_handler: ^11.0.1
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  toggle_switch: ^2.1.0
  interactive_bottom_sheet: ^1.0.0
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: YoungSerif
      fonts:
        - asset: lib\fonts\YoungSerif-Regular.ttf
    - family: TiltNeon
      fonts:
        - asset: lib\fonts\TiltNeon-Regular.ttf

  assets:
    - assets\icons\Arfanify.png
    - assets\icons\Arfanify.svg
    - assets\json\map_style.json
